// Copyright (c) Cathexis Development
// SPDX-License-Identifier: GPL-2.0-only
//
// ircv3/tags.go — IRCv3 message tag parser/builder for P10 relay.
//
// Handles the @key=value;key2=value2 tag prefix that Cathexis injects
// on P10 server-to-server lines. Acid must parse these on incoming and
// generate them on outgoing to stay in lock-step with Cathexis send.c
// and Synaxis ircv3.c.
//
// Wire format on P10 (Cathexis extension):
//   @time=2026-04-08T15:30:00.000Z;msgid=abc123;account=nick ABAAB P #channel :Hello
//   ^--- tag prefix ---^                                      ^--- normal P10 line ---^
//
// Tag escaping per IRCv3 message-tags spec:
//   \: → ; (semicolon)
//   \s → ' ' (space)
//   \\ → \ (backslash)
//   \r → CR
//   \n → LF

package ircv3

import (
	"strings"
)

// Tags represents a set of IRCv3 message tags.
// Keys starting with '+' are client-only tags (relayed but not generated by servers).
type Tags struct {
	data map[string]string
}

// NewTags creates an empty tag set.
func NewTags() *Tags {
	return &Tags{data: make(map[string]string)}
}

// TagsFromMap creates a tag set from an existing map.
func TagsFromMap(m map[string]string) *Tags {
	t := NewTags()
	for k, v := range m {
		t.data[k] = v
	}
	return t
}

// ParseTags parses an IRCv3 tag string (without the leading '@').
// Input: "time=2026-04-08T15:30:00.000Z;msgid=abc123;account=nick"
// Returns a Tags struct with the parsed key-value pairs.
func ParseTags(raw string) *Tags {
	t := NewTags()
	if raw == "" {
		return t
	}

	pairs := strings.Split(raw, ";")
	for _, pair := range pairs {
		if pair == "" {
			continue
		}
		idx := strings.IndexByte(pair, '=')
		if idx < 0 {
			// Tag with no value (boolean tag)
			t.data[pair] = ""
		} else {
			key := pair[:idx]
			val := unescapeTagValue(pair[idx+1:])
			if key != "" {
				t.data[key] = val
			}
		}
	}
	return t
}

// Get returns the value for a tag key, and whether it exists.
func (t *Tags) Get(key string) (string, bool) {
	if t == nil || t.data == nil {
		return "", false
	}
	v, ok := t.data[key]
	return v, ok
}

// Set sets a tag key-value pair.
func (t *Tags) Set(key, value string) {
	if t.data == nil {
		t.data = make(map[string]string)
	}
	t.data[key] = value
}

// Delete removes a tag by key.
func (t *Tags) Delete(key string) {
	delete(t.data, key)
}

// Has returns true if the tag key exists.
func (t *Tags) Has(key string) bool {
	_, ok := t.data[key]
	return ok
}

// Len returns the number of tags.
func (t *Tags) Len() int {
	if t == nil || t.data == nil {
		return 0
	}
	return len(t.data)
}

// Map returns a copy of the underlying map.
func (t *Tags) Map() map[string]string {
	if t == nil || t.data == nil {
		return make(map[string]string)
	}
	m := make(map[string]string, len(t.data))
	for k, v := range t.data {
		m[k] = v
	}
	return m
}

// Merge merges another tag set into this one. Existing keys are overwritten.
func (t *Tags) Merge(other *Tags) {
	if other == nil || other.data == nil {
		return
	}
	if t.data == nil {
		t.data = make(map[string]string)
	}
	for k, v := range other.data {
		t.data[k] = v
	}
}

// IsClientOnly returns true if the key is a client-only tag (prefixed with '+').
func IsClientOnly(key string) bool {
	return len(key) > 0 && key[0] == '+'
}

// ClientOnlyTags returns a new Tags containing only client-only tags.
func (t *Tags) ClientOnlyTags() *Tags {
	out := NewTags()
	for k, v := range t.data {
		if IsClientOnly(k) {
			out.data[k] = v
		}
	}
	return out
}

// ServerTags returns a new Tags containing only server tags (non '+' prefixed).
func (t *Tags) ServerTags() *Tags {
	out := NewTags()
	for k, v := range t.data {
		if !IsClientOnly(k) {
			out.data[k] = v
		}
	}
	return out
}

// String serializes the tag set to IRCv3 wire format (without the leading '@').
// Output: "account=nick;msgid=abc123;time=2026-04-08T15:30:00.000Z"
func (t *Tags) String() string {
	if t == nil || len(t.data) == 0 {
		return ""
	}

	// Build deterministic output for consistent wire format
	parts := make([]string, 0, len(t.data))
	for k, v := range t.data {
		if v == "" {
			parts = append(parts, k)
		} else {
			parts = append(parts, k+"="+escapeTagValue(v))
		}
	}
	return strings.Join(parts, ";")
}

// Prefix returns the full tag prefix for a P10 line, including the '@'.
// Returns empty string if there are no tags.
func (t *Tags) Prefix() string {
	s := t.String()
	if s == "" {
		return ""
	}
	return "@" + s
}

// escapeTagValue escapes a tag value per IRCv3 message-tags spec.
func escapeTagValue(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case ';':
			b.WriteString(`\:`)
		case ' ':
			b.WriteString(`\s`)
		case '\\':
			b.WriteString(`\\`)
		case '\r':
			b.WriteString(`\r`)
		case '\n':
			b.WriteString(`\n`)
		default:
			b.WriteByte(s[i])
		}
	}
	return b.String()
}

// unescapeTagValue unescapes a tag value per IRCv3 message-tags spec.
func unescapeTagValue(s string) string {
	if !strings.ContainsRune(s, '\\') {
		return s
	}
	var b strings.Builder
	b.Grow(len(s))
	for i := 0; i < len(s); i++ {
		if s[i] == '\\' && i+1 < len(s) {
			switch s[i+1] {
			case ':':
				b.WriteByte(';')
			case 's':
				b.WriteByte(' ')
			case '\\':
				b.WriteByte('\\')
			case 'r':
				b.WriteByte('\r')
			case 'n':
				b.WriteByte('\n')
			default:
				// Unknown escape — drop the backslash per spec
				b.WriteByte(s[i+1])
			}
			i++ // skip next char
		} else {
			b.WriteByte(s[i])
		}
	}
	return b.String()
}
